### ISSUE TITLE
Websender Error

### ISSUE THREAD

**Issue by NormanLord** [supercrafter100/Skript-projects#2]
First,I create this here because no issue can be created in that project.
Now we look at the error.
[NamelessMC] Cannot connect to your website, got an unexpected API error: API error nameless:unknown_error (meta: "SQLSTATE[HY000]: General error: 1093 You can't specify target table 'nl2_websend_console_output' for update in FROM clause"). Run /nlpl last_error to retrieve the full stack trace.

full stack trace:
[NamelessMC] com.namelessmc.plugin.lib.nameless-api.exception.ApiException: API error nameless:unknown_error (meta: "SQLSTATE[HY000]: General error: 1093 You can't specify target table 'nl2_websend_console_output' for update in FROM clause")
at Nameless-Plugin-Paper-3.4.0.jar//com.namelessmc.plugin.lib.nameless-api.RequestHandler.makeConnection(RequestHandler.java:238)
at Nameless-Plugin-Paper-3.4.0.jar//com.namelessmc.plugin.lib.nameless-api.RequestHandler.post(RequestHandler.java:58)
at Nameless-Plugin-Paper-3.4.0.jar//com.namelessmc.plugin.lib.nameless-api.modules.websend.WebsendAPI.sendConsoleLog(WebsendAPI.java:52)
at Nameless-Plugin-Paper-3.4.0.jar//com.namelessmc.plugin.common.Websend.lambda$sendLogLines$0(Websend.java:166)
at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)

I'm using nameless v2.1.0,does that matter? If it does, websender update pls.

**Comment by supercrafter100** [comment]
Websend doesn't support v2.1 and I cannot make it work as the entire event system changed
